### ISSUE TITLE
Translation to ENG

### ISSUE THREAD

**Issue by w20k** [jackfrued/Python-100-Days#1]
Hi,

Just curious, will there be English translation in near future. Looking foreword to it! Great tutorials 👍

Denis.

**Comment by jackfrued** [comment]
I will try to make it true later.

**Comment by w20k** [comment]
Thanks a lot, I hope you'll have time for that :)

**Comment by trable** [comment]
so far soo good am liking this keep up the good work fam

**Comment by ZeroCoolHacker** [comment]
When should i expect the English translation to be released?

**Comment by Sol3y** [comment]
Please translate it to English... Currently I'm using Chrome translate to use this repo ... It would be awesome if you translate it to English, please let us know when ENG version should be released.

**Comment by yarving** [comment]
如果要翻译为英文，怎么管理好一些？我可以参与一起翻译英文 :) 你有什么计划吗？ @jackfrued

**Comment by jackfrued** [comment]
> 如果要翻译为英文，怎么管理好一些？我可以参与一起翻译英文 :) 你有什么计划吗？ @jackfrued
> 
> 看了下刚才有个PR，如果继续保持现有状态的话，可以在`.md`前面加个`-ENG`以区分不同语言版本。或者用Gitbook之类的来转换。
> 
> 有很多python教程用read-the-doc（好像叫这个），可以同时支持不同版本。我觉得这样可能最好。

good idea! you can concat me by qq: 957658
