### ISSUE TITLE
day 6 同名函数定义无法覆盖 - python3

### ISSUE THREAD

**Issue by Yangfan2016** [jackfrued/Python-100-Days#118]
```py


def foo():
    print('hello, world!')


def foo():
    print('goodbye, world!')


# 下面的代码会输出什么呢？
foo()


```

pylint 提示函数已定义
```
function already defined line 29pylint(function-redefined)
```

**Comment by Flyraty** [comment]
结果是 'goodbye, world!'. pylint常用于代码风格规范检查.一个文件中同时定义2个同名函数本身不符合PEP8代码风格, 所以pylint会报警.

**Comment by Yangfan2016** [comment]
哦，这样啊😃

**Comment by Prichard407** [comment]
Welcome to the great illuminati Age of new dawns of fame, wealth, knowledge and power. Are you a business man or an Artist,Politicians or pastor and you want to become big, Powerful and famous in the world, join us to become one of our official member today. you shall be given an ideal chance to visit the illuminati and his representative after registrations is completed by you, no sacrifice, or human life needed, Illuminati brotherhood brings along wealth and famous in life, you have a full access to eradicate poverty away from your life now. it only a member who is been initiated into the church of illuminati have the authority to bring any member to the church, so before you contact any body you must be link by who is already a member, Join us today and realize your dreams. we also help out our member in protection of drugs pushing, once you become a member you will be rich and famous for the rest of your life, illuminati make there member happy so i will want you all to also be a member of the illuminati and get a tangible support of (£700,000 pounds) contact me on WhatsApp +447852680916 or mail me on Prichardmark407@outlook.com
