### ISSUE TITLE
我怀疑根本就没学到些什么

### ISSUE THREAD

**Issue by Toin1779712664** [jackfrued/Python-100-Days#165]
class类没有讲，__init__和__str__这些也没讲

**Comment by 1814931012** [comment]
day8 day9不就是讲的class吗？
你觉得没讲，那你就别看了？发出来干什么？
给别人添堵吗？
自己不想学，还要拉着别人，让别人也不学吗？


 
---原始邮件---
发件人: "Toin"<notifications@github.com>
发送时间: 2019年5月28日(星期二) 上午10:14
收件人: "jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [jackfrued/Python-100-Days] 我怀疑根本就没学到些什么 (#165)



class类没有讲，__init__和__str__这些也没讲

**Comment by Toin1779712664** [comment]
糟糕的start小号

**Comment by CHNILLJ** [comment]
I think that we should respect others' contriubtion with no reward.

**Comment by AllenLucian** [comment]
~！

**Comment by zhaoxin666666** [comment]
> I think that we should respect others' contriubtion with no reward.

year! I think you are right. some people are unfriendly and poor in spirit
