### ISSUE TITLE
Day01-15/Day04/循环结构.md下的"while循环"中的"猜数字游戏"代码有错

### ISSUE THREAD

**Issue by Kyle-Shawe** [jackfrued/Python-100-Days#182]
```python
……
while True:
    counter += 1
    number = int(input('请输入: '))
    if number < answer:
        print('大一点')  # 这里应该是'小一点'
    elif number > answer:
        print('小一点')  # 这个应该是‘大一点’
    else:
        print('恭喜你猜对了!')
        break
……
```

**Comment by 547424084** [comment]
作者的意思是 你还需要再猜的小一点或者大一点你理解的是你给出的答案相比较标准答案而言大了一点还是小了一点发自我的华为手机-------- 原始邮件 --------主题：[jackfrued/Python-100-Days] Day01-15/Day04/循环结构.md下的"while循环"中的"猜数字游戏"代码有错 (#182)发件人：Hackyle 收件人：jackfrued/Python-100-Days 抄送：Subscribed ……

while True:

    counter += 1

    number = int(input('请输入: '))

    if number < answer:

        print('大一点')  # 这里应该是'小一点'

    elif number > answer:

        print('小一点')  # 这个应该是‘大一点’

    else:

        print('恭喜你猜对了!')

        break

……
