### ISSUE TITLE
你那个薪资待遇的数据统计能给个出处吗？Python只学爬虫找不到工作。

### ISSUE THREAD

**Issue by blueskywindystar** [jackfrued/Python-100-Days#2]

**Comment by jackfrued** [comment]
jobui.com网站会有这种数据，Python的方向很多，爬虫只是其中一个处于灰色地带的领域，有公司有这种需求但是不是每个公司都有这个需求，所以从就业的角度还是做好语言基础，熟练的使用原生和常用三方库，往后还是多了解数据分析和机器学习领域的东西。

**Comment by wizardforcel** [comment]
所以。。谁让你只学爬虫了😂😂

**Comment by kissme666** [comment]
爬虫+数据分析

**Comment by jackfrued** [comment]
jobui.com
