### ISSUE TITLE
没卵用，骗小白去交钱上培训课而已

### ISSUE THREAD

**Issue by dopqob** [jackfrued/Python-100-Days#204]

**Comment by dopqob** [comment]
呵呵

**Comment by AibiTi** [comment]
支持你，请把这个问题打开。

**Comment by GreenScalpel** [comment]
去你马鼻，艹尼玛的，啥毕，腊鸡，社会人渣，见不得别人比你优秀，去你麻痹，衮啊啊衮


 
---原始邮件---
发件人: "AibiTi"<notifications@github.com>
发送时间: 2019年6月21日 21:22:23
收件人: "jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [jackfrued/Python-100-Days] 没卵用，骗小白去交钱上培训课而已 (#204)



支持你，请把这个问题打开。
