### ISSUE TITLE
Day16-20贪心的例子有点问题

### ISSUE THREAD

**Issue by AI1379** [jackfrued/Python-100-Days#247]
这个问题是0-1背包，需要用动态规划，贪心是得不到最优解的。(当然搜索也可以，但搜索的时间复杂度是O(2<sup>n</sup>)的，通常不采用)
设有N件物品，背包容量为V，第i件物品所需空间为C<sub>i</sub>，价值为W<sub>i</sub>，状态F[i,v]表示将前i件物品放入容量为v的背包中所能获得的最大价值，则状态转移方程为F[i,v]=max{F[i-1,v],F[i-1,v-C<sub>i</sub>]+W<sub>i</sub>}
贪心可以解决分数背包问题，但从例子来看，这应该是0-1背包而不是分数背包
下面这段代码可以求得背包内所装物品的最大价值，weight表示背包容量，n表示物品件数，列表v表示物品价值，列表w表示物品质量
```Python
from numpy import zeros
from numpy import int32


def solve2(vlist, wlist, totalWeight, totalLength):
    resArr = zeros((totalWeight)+1, dtype=int32)
    for i in range(1, totalLength+1):
        for j in range(totalWeight, wlist[i]-1, -1):
            if resArr[j-wlist[i]]+vlist[i] >= resArr[j]:
                resArr[j] = resArr[j-wlist[i]]+vlist[i]
    return resArr[-1]


if __name__ == '__main__':
    weight = int(input())
    n = int(input())
    v = [0, ]
    w = [0, ]
    for i in range(1, n+1):
        w.append(int(input()))
        v.append(int(input()))
    result = solve2(v, w, weight, n)
    print(result)
```
背包问题在[背包问题九讲](https://github.com/tianyicui/pack)里有详细讲解，感兴趣的可以看看

**Comment by YANLJX17** [comment]
请问怎么打开16-20天的学习文件啊，我的一点“Python语言进阶”就404了

**Comment by AI1379** [comment]
> 请问怎么打开16-20天的学习文件啊，我的一点“Python语言进阶”就404了

我是克隆下来看的，在线应该能看的呀。
可能是你网的问题

**Comment by YANLJX17** [comment]
好的👌谢谢啦！


 
---原始邮件---
发件人: "AI1379"<notifications@github.com>
发送时间: 2019年7月30日 21:17:11
收件人: "jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com>;
抄送: "YANLJX17"<2536392526@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [jackfrued/Python-100-Days] Day16-20贪心的例子有点问题 (#247)


 
请问怎么打开16-20天的学习文件啊，我的一点“Python语言进阶”就404了
  
我是克隆下来看的，在线应该能看的呀。
 可能是你网的问题

**Comment by user654321** [comment]
你的邮件已经收到，我会尽快回复。

**Comment by kenwoo666** [comment]
***@***.***

**Comment by tangwushuang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mysmomo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Twist-echo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by moffcics** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by upshalks** [comment]
您好，我是王彦林，你的邮件我已收到，我会在信息阅读后尽快回复您，谢谢！

**Comment by beatricejhx** [comment]
感谢您的来信，文件已收到，谢谢！
Thank you for your email.I’ll disposal and reply as soon as possible.

**Comment by 894221671** [comment]
您好，黄勇评已经收到您的邮件，我会在阅读后的第一时间给您回复。
