### ISSUE TITLE
循环那一节，猜字谜游戏有问题

### ISSUE THREAD

**Issue by geekxcc** [jackfrued/Python-100-Days#320]
请输入: 50
大一点
请输入: 75
小一点
请输入: 88
小一点
请输入: 85
小一点
请输入: 80
小一点
请输入: 78
小一点
请输入: 77
小一点
请输入: 76
小一点
请输入: 75
小一点
请输入: 74
小一点
请输入: 73
小一点
请输入: 72
小一点
请输入: 71
小一点
请输入: 70
小一点
请输入: 69
恭喜你猜对了!
你总共猜了15次
你的智商余额明显不足

可以猜15次呢，那个if是不是要调整一下缩进  加入那个while的代码块里面？

**Comment by baixin1225** [comment]
import random

answer = random.randint(1, 100)
counter = 0
while True:
    if counter > 7:
        print('你的智商余额明显不足,你总共猜了%d次' % counter)
        break
    counter += 1
    number = int(input('请输入: '))
    if number < answer:
        print('大一点')
    elif number > answer:
        print('小一点')
    else:
        print('恭喜你猜对了!')
        break

**Comment by baixin1225** [comment]
`import random

answer = random.randint(1, 100)
counter = 0
while True:
    if counter > 7:
        print('你的智商余额明显不足,你总共猜了%d次' % counter)
        break
    counter += 1
    number = int(input('请输入: '))
    if number < answer:
        print('大一点')
    elif number > answer:
        print('小一点')
    else:
        print('恭喜你猜对了!')
        break`
