### ISSUE TITLE
day07列表加操作

### ISSUE THREAD

**Issue by GodsDusk** [jackfrued/Python-100-Days#33]
`list1 += [1000, 2000]`
除了 += 以外还有 extend操作
这两者区分见 
[https://stackoverflow.com/questions/3653298/concatenating-two-lists-difference-between-and-extend](https://stackoverflow.com/questions/3653298/concatenating-two-lists-difference-between-and-extend)

**Comment by jackfrued** [comment]
ok

**Comment by jackfrued** [comment]
I will mention the difference in document.
