### ISSUE TITLE
day14：在tcp socket传输图片时为什么要将二进制数据处理成base64再解码成字符串？

### ISSUE THREAD

**Issue by baiyijie** [jackfrued/Python-100-Days#341]
day14：在tcp socket传输图片时为什么要将二进制数据处理成base64再解码成字符串？为什么不能直接传输二进制数据呢？

**Comment by zhanghaojiesuo** [comment]
主要是提升性能，网页加载一个图片比起加载一段base64代码所花的开销要小得多；另外在引用图片时会更加方便。
----- 原始邮件 -----
发件人：baiyijie <notifications@github.com>
收件人：jackfrued/Python-100-Days <Python-100-Days@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[jackfrued/Python-100-Days]_day14：在tcp_socket传输图片时为什么要将二进制数据处理成base64再解码成字符串？_(#341)
日期：2019年10月22日 17点07分

day14：在tcp socket传输图片时为什么要将二进制数据处理成base64再解码成字符串？为什么不能直接传输二进制数据呢？



&mdash;
