### ISSUE TITLE
day04-输入一个正整数判断是不是素数

### ISSUE THREAD

**Issue by xiongzhao1217** [jackfrued/Python-100-Days#342]
不应该开平方根，而应该取二分之一，比如10不是素数，案例中的结果是素数

**Comment by WJHPrince** [comment]
为什么不是开平方根，如果一个数x是和数，那么在(0,x^0.5]必然有其公约数啊，在(x^0.5,x)上有对应的另一个公约数，这样乘积才是x啊。

**Comment by pieces-0** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiongzhao1217"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月23日(星期三) 下午4:19
收件人:&nbsp;"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jackfrued/Python-100-Days] day04-输入一个正整数判断是不是素数 (#342)




不应该开平方根，而应该取二分之一，比如10不是素数，案例中的结果是素数
