### ISSUE TITLE
借贵宝地一用，请问go语言入门有没有如此精良优秀的repo?

### ISSUE THREAD

**Issue by GakkiGakki** [jackfrued/Python-100-Days#38]
这个教程真的一级棒，清晰易懂，面面俱到。

这一整套下来，如果能搞得清楚明白，真真的俨然一个大师了。

我想学Go语言，请问各位巨佬们有没有类似的repo推荐？

(第一次发帖，如有不妥，请折叠我)

**Comment by jasonbq** [comment]
Check this out.
[golang-developer-roadmap](https://github.com/Alikhll/golang-developer-roadmap)

**Comment by jackfrued** [comment]
good repo!!!
