### ISSUE TITLE
pymysql 依然有error

### ISSUE THREAD

**Issue by haiyang-traceto** [jackfrued/Python-100-Days#39]

**Comment by haiyang-traceto** [comment]
1.  我用的python3.7
2. 我已经在oa/__init__.py里面加入了pymysql.install_as_MySQLdb()
3. 我已经注释掉了/venv/lib/python3.7/site-packages/django/db/backends/mysql/base.py里面的raise error判断。
4. 却得到错误：
`AttributeError: 'str' object has no attribute 'decode'`

**Comment by jackfrued** [comment]
使用方式有问题！

**Comment by shouyejing** [comment]
你说的使用方式有问题是指啥，不是很清楚你的意思 


------------------ 原始邮件 ------------------
发件人: "骆昊"<notifications@github.com>;
发送时间: 2019年5月3日(星期五) 晚上8:29
收件人: "jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [jackfrued/Python-100-Days] pymysql 依然有error (#39)




使用方式有问题！
