### ISSUE TITLE
数据来源表明出处

### ISSUE THREAD

**Issue by zhoushuai0207** [jackfrued/Python-100-Days#4]
严谨，技术人员的品德之一。

**Comment by Everfighting** [comment]
赞同，很多内容都似曾相识，建议标明出处。

**Comment by jackfrued** [comment]
所有内容都是原创，可能跟我的CSDN的博客有相似的内容

**Comment by Everfighting** [comment]
@jackfrued  骆老师 我理解的zhoushuai0207的意思是文章参考的数据来源，并不是质疑您的创作。
这么有体系的文章，所以我个人估计是他才出此疑问，写论文一样的，有引用来源的那种。
