### ISSUE TITLE
day01 Python源码下载地址是否有误呢

### ISSUE THREAD

**Issue by 1977950729** [jackfrued/Python-100-Days#46]
![image](https://user-images.githubusercontent.com/10392860/57209884-f262f200-700c-11e9-85f2-5e16163f7abe.png)3.7.0的目录下去下载3.7.1的源码包，当然是提示404咯。
wget https://www.python.org/ftp/python/3.7.0/Python-3.7.1.tar.xz

**Comment by jackfrued** [comment]
Thank you for pointing out the mistakes.
