### ISSUE TITLE
pycharm教育优惠

### ISSUE THREAD

**Issue by meininghang** [jackfrued/Python-100-Days#5]
- pycharm 学生是可以申请教育优惠的,而且可以使用专业版的所有功能,我觉得增加这个信息可以让很多人减少使用盗版的欲望;
- [教育优惠官方申请指南](https://sales.jetbrains.com/hc/zh-cn/articles/207154369)
- 此外,不建议让新手去使用 IDE, 功能过于强大对于新手并非是好事, vs code 和 jupyter notebook 更适合, 
 轻量级编辑器前期学习足够了.
- 加油!!!

**Comment by CoolerMe** [comment]
谢谢分享!:-)

**Comment by meininghang** [comment]
@CoolerMe 望周知，减少盗版。:smiley:
