### ISSUE TITLE
41~55部分

### ISSUE THREAD

**Issue by JesisWang** [jackfrued/Python-100-Days#500]
这部分在41,42中挺详细的，都能够理解，但是后面的章节经常是出现一段代码或新的概念，但是不知道代码应该放在哪里，是新建一个文件还是放在某些文件内，特别是我这种小白，头晕

**Comment by moon-zhangyue** [comment]
def的基本都在views.py
class的在models.py
path在urls.py
html的在templates文件夹
结合着41，42和Django文档看 这段代码干啥的  这里面许多引用都没写 但是前面课程讲了

**Comment by JesisWang** [comment]
嗯，研究了一下才弄懂，主要是之前没基础，谢谢
