### ISSUE TITLE
Python-100-Days

### ISSUE THREAD

**Issue by pzb5090** [jackfrued/Python-100-Days#522]

**Comment by pzb5090** [comment]
>

**Comment by LeoMacArthur** [comment]
unsubscribe




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pzb5090"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 晚上10:58
收件人:&nbsp;"jackfrued/Python-100-Days"<Python-100-Days@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [jackfrued/Python-100-Days] Python-100-Days (#522)





 
Closed #522.
