### ISSUE TITLE
处理Excel时报错 ModuleNotFoundError: No module named 'openpyxl'

### ISSUE THREAD

**Issue by chellChang** [jackfrued/Python-100-Days#709]
我在终端 pip3 install openpyxl 下载完成后，运行仍然报上面的错误，怎么解决的啊

**Comment by Kirs1124** [comment]
> 我在终端 pip3 install openpyxl 下载完成后，运行仍然报上面的错误，怎么解决的啊

卸载重装一下试一试

**Comment by chellChang** [comment]
> > 我在终端 pip3 install openpyxl 下载完成后，运行仍然报上面的错误，怎么解决的啊
> 
> 卸载重装一下试一试
