### ISSUE TITLE
部分公式解析不了

### ISSUE THREAD

**Issue by 10ngui** [jackfrued/Python-100-Days#72]
$${\displaystyle F_{0}=0}$$

$${\displaystyle F_{1}=1}$$

$${\displaystyle F_{n}=F_{n-1}+F_{n-2}}({n}\geq{2})$$

**Comment by 10ngui** [comment]
如果老师没时间，我可以稍后提交修复的pr:smile:

**Comment by 10ngui** [comment]
正确的公式表达需要加中括号`[ ]`,比如：`[$${\displaystyle s=a_{1}a_{2}\dots a_{n}(0\leq n \leq \infty)}$$]`，部分小问题

**Comment by Geekya215** [comment]
**GFM(GitHub Flavored Markdown)** 不支持渲染LaTeX公式,关于这个问题我已经提过PR了,参见这里=> #70

**Comment by Geekya215** [comment]
@10ngui 
**GFM(GitHub Flavored Markdown)** 不支持渲染LaTeX公式,关于这个问题我已经提过PR了,参见这里=> #70

**Comment by 10ngui** [comment]
> @10ngui
> **GFM(GitHub Flavored Markdown)** 不支持渲染LaTeX公式,关于这个问题我已经提过PR了,参见这里=> #70

明白了，老师文档中部分公式是可以跳转到正确地址的，像这样：`[$${\displaystyle s=a_{1}a_{2}\dots a_{n}(0\leq n \leq \infty)}$$](https://wikimedia.org/api/rest_v1/media/math/render/svg/e29bf631b090323edd6889f810e6cff29538b161)`应该是用到了wikimedia的api，部分解析不了应该是老师手误，个人觉得你

**Comment by 10ngui** [comment]
> @10ngui
> **GFM(GitHub Flavored Markdown)** 不支持渲染LaTeX公式,关于这个问题我已经提过PR了,参见这里=> #70

明白了，老师文档中部分公式是可以跳转到正确地址的，像这样：`[$${\displaystyle s=a_{1}a_{2}\dots a_{n}(0\leq n \leq \infty)}$$](https://wikimedia.org/api/rest_v1/media/math/render/svg/e29bf631b090323edd6889f810e6cff29538b161)`老师是用到了wikimedia的api，部分解析不了应该是老师手误，个人觉得你改外链图片的话可以等到老师完结后补充，不然会影响到老师原本的写法:smile

**Comment by Geekya215** [comment]
@10ngui 

你说的这个不是跳转的问题,他就这里就是打算直接引用图片,只不过他没写对,正确是写法应该是这样`![这里可有可无,但是后面()里的URL一定要正确](https://wikimedia.org/api/rest_v1/media/math/render/svg/e29bf631b090323edd6889f810e6cff29538b161)`
他在`[]`前面少写了一个`!`  ,就直接渲染成超链接了

**具体效果:**

✔️ ![$${\displaystyle s=a_{1}a_{2}\dots a_{n}(0\leq n \leq \infty)}$$](https://wikimedia.org/api/rest_v1/media/math/render/svg/e29bf631b090323edd6889f810e6cff29538b161)

❌ [$${\displaystyle s=a_{1}a_{2}\dots a_{n}(0\leq n \leq \infty)}$$](https://wikimedia.org/api/rest_v1/media/math/render/svg/e29bf631b090323edd6889f810e6cff29538b161)

PS:我在PR里是用[CodeCogs](https://www.codecogs.com/latex/eqneditor.php)把公式转成图片下载到本地引用,并没用使用外链, 因为担心后面链接失效或者是~GFW~等原因. 其实最好的解决办法是安装[MathJax Plugin for Github](https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima?hl=en)插件,可以不用更改文档里的公式.
