### ISSUE TITLE
day42中django运行报错

### ISSUE THREAD

**Issue by yangkai21** [jackfrued/Python-100-Days#829]
大佬们好，我想请问一下我在检查渲染教师页面时发现运行出现这句报错，request.GET.get（‘sno’）获取到的是一个‘nonetype’类型的值，请问我是哪里没搞对吗？
![XQM(DZ7KFIF1R{`L@342 XK](https://user-images.githubusercontent.com/86920956/139857809-3fa0650d-8401-49b1-b5b9-846c2884c3d9.png)

**Comment by jxsdegit** [comment]
我也遇到了这个错误，请问你是怎么解决的呢
