### ISSUE TITLE
Day02华氏转摄氏温度公式有问题

### ISSUE THREAD

**Issue by 45min-on-the-git** [jackfrued/Python-100-Days#911]
原文中是：$C=(F - 32) \div 1.8$
这个\div是啥，而且下面代码实例也写了：c = (f - 32) / 1.8
所以是不是编写的有问题

**Comment by xiongbinzou** [comment]
这里应该是打算写公式的，
$$C=(F - 32) \div 1.8$$
这个是Markdown语法，公式应该由两个$$包围起来，作者忘记写了
