### ISSUE TITLE
day 7 部分显示出现问题

### ISSUE THREAD

**Issue by jianzhao0806** [jackfrued/Python-100-Days#94]
除了上面提到的生成器语法，Python中还有另外一种定义生成器的方式，就是通过yield关键字将一个普通函数改造成生成器函数。下面的代码演示了如何实现一个生成斐波拉切数列的生成器。所谓斐波拉切数列可以通过下面递归的方法来进行定义：

$${\displaystyle F_{0}=0}$$

$${\displaystyle F_{1}=1}$$

$${\displaystyle F_{n}=F_{n-1}+F_{n-2}}({n}\geq{2})$$

**Comment by jackfrued** [comment]
renderers for math formula is not so smart in github.
